services:
  engine:
    image: ghcr.io/grantbest/betting-application/engine:main
    container_name: mlb_engine_prod
    networks:
      - homelab_global
    environment:
      APP_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: homelab
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_HOST: redis
    restart: always

  frontend:
    image: ghcr.io/grantbest/betting-application/frontend:main
    container_name: mlb_frontend_prod
    networks:
      - homelab_global
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/homelab
      DEV_URL: https://dev.bestfam.us
      PROD_URL: https://bestfam.us
      DISCORD_CHANNEL_URL: https://discord.com/channels/1234567890/1234567890
    ports:
      - "3000:3000"
    restart: always

networks:
  homelab_global:
    external: true
